export enum UserRank {
	None = "",
	AirmanBasic = "AB.",
	Airman = "Amn.",
	AirmanFirstClass = "A1C.",
	SeniorAirman = "SrA.",
	StaffSergeant = "SSgt.",
	TechnicalSergeant = "TSgt.",
	MasterSergeant = "MSgt.",
	SeniorMasterSergeant = "SMSgt.",
	ChiefMasterSergeant = "CMSgt.",
	SecondLieutenant = "2nd Lt.",
	FirstLieutenant = "1st Lt.",
	Captain = "Capt.",
	Major = "Maj.",
	LieutenantColonel = "Lt. Col.",
	Colonel = "Col.",
	BrigadierGeneral = "Brig. Gen.",
	MajorGeneral = "Maj. Gen.",
	LieutenantGeneral = "Lt. Gen.",
	General = "Gen.",
}
